### ISSUE TITLE
Error While trying to install template

### ISSUE THREAD

**Issue by 0cwa** [YunoHost-Apps/SitemagicCMS_ynh#3]
YNH v4.3.5, Debian VPS
I get this error on index.php?SMExt=SMConfig after trying to install an installed template.  By the way, I also get an error when I try to disable tips, it'll say an error occurred, tips might not be disabled and they aren't.
```
An unhandled error occured

Unable to open or create file '/var/www/sitemagiccms/base/../config.xml.php' for writing

Stack trace

#0 /var/www/sitemagiccms/base/SMConfiguration.class.php(210): SMTextFileWriter->__construct('/var/www/sitema...', 'Overwrite')
#1 /var/www/sitemagiccms/extensions/SMConfig/FrmConfig.class.php(716): SMConfiguration->Commit()
#2 /var/www/sitemagiccms/extensions/SMConfig/FrmConfig.class.php(318): SMConfigFrmConfig->saveConfiguration()
#3 /var/www/sitemagiccms/extensions/SMConfig/FrmConfig.class.php(66): SMConfigFrmConfig->handlePostBack()
#4 /var/www/sitemagiccms/extensions/SMConfig/Main.class.php(43): SMConfigFrmConfig->__construct(Object(SMContext))
#5 /var/www/sitemagiccms/base/SMController.class.php(400): SMConfig->Render()
#6 /var/www/sitemagiccms/base/SMController.class.php(193): SMController->loadExtension('SMConfig')
#7 /var/www/sitemagiccms/index.php(27): SMController->Execute()
#8 {main}
```

**Comment by tituspijean** [comment]
Can you run the following command in the CLI and share its output?

`ls -la /var/www/sitemagiccms/base/../`

**Comment by 0cwa** [comment]
```
# ls -la /var/www/sitemagiccms/base/../
total 152
drwxr-x---   9 sitemagiccms www-data      4096 Jan 19 13:29 .
drwxr-xr-x+ 15 root         root          4096 Jan 19 13:29 ..
drwxr-x---   5 sitemagiccms www-data      4096 Oct 18  2019 base
-rw-r-----   1 sitemagiccms www-data     31371 Oct 18  2019 changelog.txt
-r--------   1 sitemagiccms sitemagiccms  4030 Jan 19 13:29 config.xml.php
drwxr-x---   2 sitemagiccms www-data      4096 Oct 18  2019 data
drwxr-x---  23 sitemagiccms www-data      4096 Oct 18  2019 extensions
-rw-r-----   1 sitemagiccms www-data      1150 Oct 18  2019 favicon.ico
drwxr-x---   5 sitemagiccms www-data      4096 Oct 18  2019 files
-rw-r-----   1 sitemagiccms www-data        12 Jan 19 13:29 .gitignore
drwxr-x---   8 sitemagiccms www-data      4096 Oct 18  2019 images
-rw-r-----   1 sitemagiccms www-data      1100 Oct 18  2019 index.php
-rw-r-----   1 sitemagiccms www-data     21928 Oct 18  2019 install.php
-rw-r-----   1 sitemagiccms www-data      2452 Oct 18  2019 license.txt
-rw-r-----   1 sitemagiccms www-data       575 Oct 18  2019 metadata.xml
-rw-r-----   1 sitemagiccms www-data       709 Oct 18  2019 package.json
drwxr-x---   2 sitemagiccms www-data      4096 Oct 18  2019 sites
-rw-r-----   1 sitemagiccms www-data      6237 Oct 18  2019 tables.sql
drwxr-x---  15 sitemagiccms www-data      4096 Oct 18  2019 templates
-rw-r-----   1 sitemagiccms www-data     21928 Oct 18  2019 upgrade.php

```

**Comment by tituspijean** [comment]
Both errors are due to the fact that the CMS needs to be able to rewrite its config file. I will propose a fix shortly.

**Comment by tituspijean** [comment]
@0cwa you can try this fix with the command `yunohost app upgrade sitemagiccms -u https://github.com/YunoHost-Apps/SitemagicCMS_ynh/tree/testing -F`
